# Generated by Django 3.1 on 2020-08-06 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.author'),
        ),
    ]
