# Generated by Django 3.1 on 2020-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20200806_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_req',
            field=models.TextField(default=10),
        ),
    ]
