# Generated by Django 3.1 on 2020-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipe_time_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_req',
            field=models.TextField(default=None, max_length=10),
        ),
    ]
